import _legacy from './legacy.js';
import _shades_classic from './shades-classic.js';
import _shades_grey from './shades-grey.js';
import _rect from './rect.js';
var defaultExport = {};
var __exports;
var legacy;
var shades_classic;
var shades_grey;
var rect;
__exports = {};
defaultExport = __exports;
legacy = _legacy;
var legacy0 = legacy;
shades_classic = _shades_classic;
var shades_classic0 = shades_classic;
shades_grey = _shades_grey;
var shades_grey0 = shades_grey;
rect = _rect;
var rect0 = rect;
defaultExport.legacy = legacy0;
defaultExport.shades_classic = shades_classic0;
defaultExport.shades_grey = shades_grey0;
defaultExport.rect = rect0;
export default defaultExport;