var defaultExport = {};
var __exports;
var format;
var barCompleteChar;
var barIncompleteChar;
__exports = {};
defaultExport = __exports;
format = 'progress [{bar}] {percentage}% | ETA: {eta}s | {value}/{total}';
var format0 = format;
barCompleteChar = '=';
var barCompleteChar0 = barCompleteChar;
barIncompleteChar = '-';
var barIncompleteChar0 = barIncompleteChar;
defaultExport.format = format0;
defaultExport.barCompleteChar = barCompleteChar0;
defaultExport.barIncompleteChar = barIncompleteChar0;
export default defaultExport;