var __exports;
var format;
var barCompleteChar;
var barIncompleteChar;
__exports = {};
module.exports = __exports;
format = 'progress [{bar}] {percentage}% | ETA: {eta}s | {value}/{total}';
module.exports.format = format;
barCompleteChar = '=';
module.exports.barCompleteChar = barCompleteChar;
barIncompleteChar = '-';
module.exports.barIncompleteChar = barIncompleteChar;