var __exports;
var format;
var barCompleteChar;
var barIncompleteChar;
__exports = {};
module.exports = __exports;
format = ' {bar} {percentage}% | ETA: {eta}s | {value}/{total}';
module.exports.format = format;
barCompleteChar = '\u2588';
module.exports.barCompleteChar = barCompleteChar;
barIncompleteChar = '\u2591';
module.exports.barIncompleteChar = barIncompleteChar;