import _colors from 'colors';
var defaultExport = {};
var __exports;
var format;
var barCompleteChar;
var barIncompleteChar;
__exports = {};
defaultExport = __exports;
format = _colors.grey(' {bar}') + ' {percentage}% | ETA: {eta}s | {value}/{total}';
var format0 = format;
barCompleteChar = '\u2588';
var barCompleteChar0 = barCompleteChar;
barIncompleteChar = '\u2591';
var barIncompleteChar0 = barIncompleteChar;
defaultExport.format = format0;
defaultExport.barCompleteChar = barCompleteChar0;
defaultExport.barIncompleteChar = barIncompleteChar0;
export default defaultExport;